owner: shared-properties
repo: uptime

sites:
  - name: www
    url: https://www.shared.properties/
  - name: api
    url: https://api.shared.properties/api
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{
      "operationName":"Me",
      "variables":{},
      "query":"query Me {
        me {
          __typename
        }
      }"
    }'

status-website:
  cname: status.shared.properties
  favicon: https://www.shared.properties/favicon/favicon-228.png
  logoUrl: https://www.shared.properties/images/logos/sidebar.svg
  css: "footer { display: none; }"
  name: "Status: shared.properties"
  introTitle: "Service status for Shared Properties"
  introMessage: "This site communicates if services are experiencing technical difficulties. This information is automated and not manually managed."
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: www
      href: https://www.shared.properties
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/shared-properties/uptime
