owner: shared-properties
repo: uptime

sites:
  - name: www
    url: https://www.shared.properties/
  - name: api
    url: https://api.shared.properties/api
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{
      "operationName":"Me",
      "variables":{},
      "query":"query Me {
        me {
          __typename
        }
      }"}'

status-website:
  cname: status.shared.properties
  favicon: https://www.shared.properties/favicon/favicon-228.png
  logoUrl: https://www.shared.properties/images/logos/sidebar.svg
  name: Shared Properties Status
  introTitle: "Status page for Shared Properties"
  introMessage: ""
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: www
      href: https://www.shared.properties
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/shared-properties/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
